# Generated by Django 4.1.7 on 2023-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoAdocao',
        ),
    ]
