# Generated by Django 4.1.7 on 2023-03-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoadocao',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando aprovação'), ('AP', 'Aprovado'), ('R', 'Recusado')], default='AG', max_length=2),
        ),
    ]
